project:
  type: book
  output-dir: docs

book:
  title: "AI for the Sceptical Scholar: Practical Strategies for Using LLMs in Research"
  author: "Teal Emery"
  date: "7/15/2025"
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: "Foundations"
      chapters:
        - foundations_intro.qmd         # Chapter 1.1
        - foundations_considerations.qmd  # Chapter 1.2

    - part: "Practical Applications"
      chapters:
        - apps_prompting.qmd          # Chapter 2.1
    #     - apps_gems.qmd               # Chapter 2.2
    #     - apps_lit_review.qmd         # Chapter 2.3
    #     - apps_translation.qmd        # Chapter 2.4
    #     - apps_coding.qmd             # Chapter 2.5
    #     - apps_other_tools.qmd        # Chapter 2.6
    # 
    # - part: "Advanced Possibilities"
    #   chapters:
    #     - advanced_casestudy.qmd      # Chapter 3.1
    #     - advanced_programmatic.qmd   # Chapter 3.2
    #     - advanced_validation.qmd     # Chapter 3.3
    # 
    # - part: "Q&A and Discussion"
    #   chapters:
    #     - discussion_qa.qmd           # Chapter 4.1
    #     - discussion_next_steps.qmd   # Chapter 4.2
    # 
    # - part: "Appendices"
    #   chapters:
    #     - appendix_quick_start.qmd
    #     - appendix_templates.qmd
    #     - appendix_resources.qmd
    #     - appendix_ethics.qmd
    # 
    # - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual
